### ISSUE TITLE
Potential performance problem with a number of event listeners

### ISSUE THREAD

**Issue by pavelsher** [rodm/teamcity-jmx-plugin#1]
It looks like this plugin registers a listener for each project. Listeners are lightweight, but still the number of them can be huge on some installations. For instance in one of the thread dumps I've seen:
TC: 12:53:13 Processing 3823 listeners for buildInterrupted

Seems majority of them were teamcity.jmx.BuildStatistics objects. Note: there are installations of TeamCity with more than 10k projects..

It'd be better and more efficient to have one listener for all projects instead.

**Comment by rodm** [comment]
Thanks for the feedback I'll take a look at changing this.

**Comment by rodm** [comment]
I've uploaded a new version, v1.2, that addresses the performance issues you raised and fixes a few other issues related to JMX.
